# Generated by Django 4.0.6 on 2022-12-06 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=200)),
                ('_age', models.IntegerField(null=True)),
                ('_department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
    ]
