# Generated by Django 4.0.6 on 2022-12-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='_department_id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='_employee_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='_name',
            new_name='name',
        ),
    ]
