# Generated by Django 4.0.6 on 2022-12-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('_department_name', models.CharField(max_length=50)),
            ],
        ),
    ]
