# Generated by Django 4.0.6 on 2022-12-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='_department_id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='_department_name',
            new_name='department_name',
        ),
    ]
